repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: check-toml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [--line-length=120]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
      - id: mypy
        exclude: "^tests"
        args:
          - --config-file=pyproject.toml
          - --no-warn-unused-ignores
        additional_dependencies: [types-PyYAML]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.8.0
    hooks:
      - id: isort
        args: [--tc, --multi-line 3]
  - repo: local
    hooks:
      - id: trufflehog
        name: TruffleHog
        description: Detect secrets in your data.
        entry: bash -c 'docker run --rm -v "$PWD:/src" ghcr.io/trufflesecurity/trufflehog:latest git --branch=HEAD file:///src --fail --only-verified'
        language: system
        stages: ["commit", "push"]
  - repo: local
    hooks:
      - id: semgrep
        name: semgrep
        entry: bash -c 'docker run --rm -v "$PWD:/src" returntocorp/semgrep semgrep --config p/ci --error --skip-unknown-extensions'
        language: system
        stages: ["commit", "push"]
